twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Twig\Components\: 'components/'
twig:
    default_path: '%kernel.project_dir%/templates'
    # (ou des paths additionnels)
